const projects = [
  {
    id: 'gitflowai',
    title: 'GitFlowAI',
    img: '/project1/project1.webp',
    link: '/projects/gitflowai',
    date: '2024',
    liveLink: undefined,
    company: 'Personal Project',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'GitFlowAI is a developer tool that transforms GitHub repositories into interactive flowcharts using Llama 3 LLM. Built with Next.js 15 and TypeScript, it serves 200+ users with real-time code analysis.',
      'The platform features OAuth authentication, MySQL database for secure token management, and interactive D3.js visualizations that render complex codebase architecture with zoom/pan capabilities.',
      'By automating logic flow generation and visual mapping, GitFlowAI reduces codebase comprehension time by 70%, making it easier for developers to understand large codebases at a glance.',
    ],
  },
  {
    id: 'resumex',
    title: 'ResumeX',
    img: '/project2/project2.webp',
    link: '/projects/resumex',
    date: '2024',
    company: 'Personal Project',
    liveLink: undefined,
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'ResumeX is a comprehensive full-stack career development platform with AI resume analysis and mock interview system. The platform handles 500+ concurrent users and 1000+ API requests daily.',
      'Architected with Express.js and MySQL, featuring Razorpay payment gateway integration, subscription system with usage tracking, and secure authentication using JWT and bcrypt.',
      'Developed 4 AI-powered virtual mentors using OpenAI and Gemini APIs for personalized career guidance, plus a mock interview system with real-time scoring across 5 categories and detailed performance analytics.',
    ],
  },
  {
    id: 'ghostscribe',
    title: 'GhostScribe',
    img: '/project3/project3.webp',
    link: '/projects/ghostscribe',
    date: '2024',
    liveLink: undefined,
    company: 'Personal Project',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'GhostScribe is an AI-powered developer assistant that generates production-ready full-stack code from natural language descriptions. Built using Next.js and integrated with large language models for context-aware code generation.',
      'The tool features customizable output templates for React and Node.js applications, enabling developers to quickly prototype and build applications with minimal boilerplate code.',
      'By automating code generation, GhostScribe reduces prototyping time by 60%, allowing developers to focus on implementing business logic rather than writing repetitive boilerplate code.',
    ],
  },
  {
    id: 'baatcheet',
    title: 'BaatCheet',
    img: '/project4/project4.webp',
    link: '/projects/baatcheet',
    date: '2024',
    company: 'Personal Project',
    liveLink: undefined,
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'BaatCheet is a peer-to-peer video/audio calling platform with low-latency real-time communication. Built with React and WebRTC protocols for efficient media streaming and connection management.',
      'The platform features responsive UI with React and Vite, supporting 50+ concurrent users with text messaging and real-time synchronization across multiple devices.',
      'With sub-100ms latency, BaatCheet provides seamless communication experience, making it ideal for remote collaboration, online meetings, and real-time interactions.',
    ],
  },
  {
    id: 'persperence',
    title: 'Persperence Envision',
    img: '/project5/project5.webp',
    link: '/projects/persperence',
    date: '2024',
    company: 'Persperence Envision',
    liveLink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Developed and optimized 3+ production-ready web pages for commercial application serving 500+ users. Integrated Razorpay payment gateway and Firebase authentication, reducing payment processing time by 40%.',
      'Implemented responsive UI components using React.js, improving mobile user experience by 35%. Collaborated with cross-functional team of 5 developers using Git version control.',
      'The project involved building scalable frontend components with focus on performance optimization and user experience, resulting in significant improvements in both functionality and usability.',
    ],
  },
];
export default projects;
